# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 01:45
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('main_img', '1200x350', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
