# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 16:03
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20160521_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u0418\u043c\u044f')),
                ('date_from', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u0435\u0437\u0434\u0430')),
                ('date_to', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0432\u044b\u0435\u0437\u0434\u0430')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u041e\u0442\u0437\u044b\u0432')),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=30, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
