# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 18:08
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20160524_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('main_text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443 \u0443\u0441\u043b\u0443\u0433')),
                ('main_img', models.ImageField(upload_to='./img', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443 \u0443\u0441\u043b\u0443\u0433')),
                ('cropping', image_cropping.fields.ImageRatioField('main_img', '380x300', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('more', models.BooleanField(default=False, verbose_name='\u041f\u043e\u0434\u0440\u043e\u0431\u043d\u0435\u0435')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u041f\u043e\u0434\u0440\u043e\u0431\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442')),
            ],
        ),
    ]
