# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_auto_20160531_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='allow',
            field=models.BooleanField(default=False, verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u0442\u044c'),
        ),
    ]
