# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-01 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_reviews_allow'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='main',
            field=models.BooleanField(default=False, verbose_name='\u041d\u0430 \u0433\u043b\u0430\u0432\u043d\u0443\u044e'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('main_img', '350x235', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
