# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_auto_20160602_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serv_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='./img', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Service')),
            ],
        ),
    ]
