# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-07 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_date_room_ind_tenants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_ind',
            name='stat',
            field=models.CharField(choices=[('\u0417\u0430\u043d\u044f\u0442', 'reserved'), ('\u0421\u0432\u043e\u0431\u043e\u0434\u0435\u043d', 'free'), ('\u041d\u0435 \u0440\u0430\u0431\u043e\u0442\u0430\u0435\u0442', 'disable')], max_length=20, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
    ]
