# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-21 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_auto_20160707_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='Tenants',
        ),
    ]
