# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-21 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_auto_20160721_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u0435\u0437\u0434\u0430')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0432\u044b\u0435\u0437\u0434\u0430')),
            ],
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
            ],
        ),
        migrations.AddField(
            model_name='date',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Tenants'),
        ),
        migrations.AddField(
            model_name='date',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Room_ind'),
        ),
    ]
