# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-22 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_auto_20160722_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_from', models.IntegerField(verbose_name='\u0413\u043e\u0434 \u043f\u0440\u0438\u0435\u0437\u0434\u0430')),
                ('year_to', models.IntegerField(verbose_name='\u0413\u043e\u0434 \u043e\u0442\u044a\u0435\u0437\u0434\u0430')),
                ('month_from', models.IntegerField(verbose_name='\u041c\u0435\u0441\u044f\u0446 \u043f\u0440\u0438\u0435\u0437\u0434\u0430')),
                ('month_to', models.IntegerField(verbose_name='\u041c\u0435\u0441\u044f\u0446 \u043e\u0442\u044a\u0435\u0437\u0434\u0430')),
                ('day_from', models.IntegerField(verbose_name='\u0414\u0435\u043d\u044c \u043f\u0440\u0438\u0435\u0437\u0434\u0430')),
                ('day_to', models.IntegerField(verbose_name='\u0414\u0435\u043d\u044c \u043e\u0442\u044a\u0435\u0437\u0434\u0430')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Tenants')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Room_ind')),
            ],
        ),
    ]
