# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='name',
        ),
        migrations.RemoveField(
            model_name='date',
            name='number',
        ),
        migrations.AlterField(
            model_name='room_ind',
            name='stat',
            field=models.CharField(choices=[('avaible', '\u0420\u0430\u0431\u043e\u0442\u0430\u0435\u0442'), ('disable', '\u041d\u0435 \u0440\u0430\u0431\u043e\u0442\u0430\u0435\u0442')], max_length=20, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
    ]
