# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_auto_20160731_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u0435\u0437\u0434\u0430')),
                ('date_to', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0432\u044b\u0435\u0437\u0434\u0430')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Tenants')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Room_ind')),
            ],
        ),
    ]
