# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-02 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='october',
            field=models.IntegerField(default=1, verbose_name='\u041e\u043a\u0442\u044f\u0431\u0440\u044c'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='september',
            field=models.IntegerField(default=1, verbose_name='\u0421\u0435\u043d\u0442\u044f\u0431\u0440\u044c'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='other',
            field=models.IntegerField(verbose_name='\u041d\u043e\u044f\u0431\u0440\u044c-\u0410\u043f\u0440\u0435\u043b\u044c'),
        ),
    ]
