# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_auto_20160803_0012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenants',
        ),
    ]
