# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_auto_20160926_0219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
