# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_auto_20160926_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('first_name', models.CharField(max_length=30, verbose_name='\u0418\u043c\u044f')),
                ('second_name', models.CharField(max_length=30, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('date_birthday', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('pass_data', models.TextField(verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('firm', models.CharField(max_length=30, verbose_name='\u0422\u0443\u0440\u0444\u0438\u0440\u043c\u0430')),
                ('date_from', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u0435\u0437\u0434\u0430')),
                ('date_to', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0432\u044b\u0435\u0437\u0434\u0430')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Room_ind')),
            ],
        ),
    ]
